spring:
  application:
    name: a
  datasource:
    url: jdbc:mysql://localhost:3306/a?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    time-zone: Asia/Shanghai

mybatis:
  config-location: classpath:db/mybatis/config.xml